[package]
name = "bicycle"
version = "0.1.0"
authors = ["Brainium Studios LLC", "Francesca Lovebloom <francesca@brainiumstudios.com>"]
edition = "2018"
description = "Handlebars with wheels. ğŸš´ğŸ½â€â™€ï¸"
documentation = "https://docs.rs/bicycle"
repository = "https://github.com/BrainiumLLC/bicycle"
readme = "README.md"
keywords = ["templating", "handlebars"]
license = "Apache-2.0/MIT"

[dependencies]
handlebars = "3.3.0"
log = "0.4.11"
serde = "1.0.114"
serde_json = "1.0.57"
thiserror = "1.0.20"
